server:
  log_level: info

logs:
  configs:
  - name: subtitles-logs
    clients:
      - url: ${LOKI_URL}
        basic_auth:
          username: ${LOKI_USERNAME}
          password: ${LOKI_API_KEY}
        timeout: 10s
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: docker
        docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 10s
        relabel_configs:
          - source_labels: ['__meta_docker_container_name']
            regex: '.*azureuser-frontend.*'
            action: keep
          - target_label: "job"
            replacement: "subtitles-logs"

metrics:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
  configs:
    - name: subtitles-metrics
      remote_write:
        - url: ${PROMETHEUS_URL}
          basic_auth:
            username: ${PROMETHEUS_USERNAME}
            password: ${PROMETHEUS_API_KEY}
      scrape_configs:
        - job_name: docker
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 15s
          relabel_configs:
            - source_labels: ['__meta_docker_container_label_prometheus_io_scrape']
              regex: "true"
              action: keep
            - source_labels: ['__meta_docker_container_label_prometheus_io_port']
              target_label: __metrics_path__
              regex: (.+)
              replacement: /metrics
            - source_labels: ['__meta_docker_container_label_prometheus_io_path']
              target_label: __metrics_path__
              regex: (.+)
              replacement: $1
            - source_labels: ['__meta_docker_container_name']
              target_label: container_name
              regex: /(.*)
              replacement: $1

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true