services:
  frontend:
    image: ateulerlabs/ai-subtitler-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - /home/azureuser/frontend.env
    volumes:
      - /home/azureuser/service-account-credentials/service-account.json:/app/credentials/service-account.json
      - /home/azureuser/database:/app/database
    restart: unless-stopped
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=3000"
      - "prometheus.io/path=/metrics"

  grafana-agent:
    image: grafana/agent:latest
    volumes:
      - /home/azureuser/agent-config.yml:/etc/agent-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--config.file=/etc/agent-config.yml"
    env_file:
      - /home/azureuser/metrics.env
    ports:
      - "3011:3011"
    restart: unless-stopped

  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=openai_whisper
      - ASR_MODEL_PATH=/app/models
    volumes:
      - /home/azureuser/models/model_file:/app/models
      - /home/azureuser/models/.cache:/root/.cache/
    restart: unless-stopped
