services:
  frontend:
    image: ateulerlabs/ai-subtitler-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - /home/azureuser/frontend.env
    volumes:
      - /home/azureuser/service-account-credentials/service-account.json:/app/credentials/service-account.json
      - /home/azureuser/database:/app/database
    restart: unless-stopped