name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'next-frontend/**'
              - '.github/workflows/docker-build.yml'

  build-next-app:
    needs: check_changes
    if: needs.check_changes.outputs.frontend_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    concurrency:
      group: frontend-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history to ensure all files are available

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: List directory contents for debugging
        run: ls -la ./next-frontend/lib/

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./next-frontend
          file: ./next-frontend/Dockerfile
          build-args: |
            NEXT_PUBLIC_ENV=production
            NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY=${{ secrets.APP_INSIGHTS_INSTRUMENTATION_KEY }}
          push: true
          tags: |
            ateulerlabs/ai-subtitler-frontend:latest
            ateulerlabs/ai-subtitler-frontend:${{ github.sha }}
