name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'next-frontend/**'
      - 'python-backend/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-next-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.commits[0].modified, 'next-frontend/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./next-frontend
          file: ./next-frontend/Dockerfile
          build-args: |
            AI_BACKEND_URL=localhost:5007
          push: true
          tags: |
            ateulerlabs/ai-subtitler-frontend:latest
            ateulerlabs/ai-subtitler-frontend:${{ github.sha }}

  build-python-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.commits[0].modified, 'python-backend/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./python-backend
          file: ./python-backend/Dockerfile
          push: true
          tags: |
            ateulerlabs/ai-subtitler-backend:latest
            ateulerlabs/ai-subtitler-backend:${{ github.sha }} 